# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from agent import embedding_pb2 as embedding__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in embedding_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EmbeddingServiceStub(object):
    """EmbeddingService provides embedding operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Embed = channel.unary_unary(
                '/agent.embedding.EmbeddingService/Embed',
                request_serializer=embedding__pb2.EmbedRequest.SerializeToString,
                response_deserializer=embedding__pb2.EmbedResponse.FromString,
                _registered_method=True)
        self.BatchEmbed = channel.unary_unary(
                '/agent.embedding.EmbeddingService/BatchEmbed',
                request_serializer=embedding__pb2.BatchEmbedRequest.SerializeToString,
                response_deserializer=embedding__pb2.EmbedResponse.FromString,
                _registered_method=True)
        self.GetModelInfo = channel.unary_unary(
                '/agent.embedding.EmbeddingService/GetModelInfo',
                request_serializer=embedding__pb2.ModelInfoRequest.SerializeToString,
                response_deserializer=embedding__pb2.ModelInfoResponse.FromString,
                _registered_method=True)
        self.ClearCache = channel.unary_unary(
                '/agent.embedding.EmbeddingService/ClearCache',
                request_serializer=embedding__pb2.ClearCacheRequest.SerializeToString,
                response_deserializer=embedding__pb2.ClearCacheResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/agent.embedding.EmbeddingService/HealthCheck',
                request_serializer=embedding__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=embedding__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class EmbeddingServiceServicer(object):
    """EmbeddingService provides embedding operations
    """

    def Embed(self, request, context):
        """Embed creates embeddings for texts
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchEmbed(self, request, context):
        """BatchEmbed creates embeddings for a large batch
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelInfo(self, request, context):
        """GetModelInfo returns model information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearCache(self, request, context):
        """ClearCache clears the embedding cache
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """HealthCheck checks the service health
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmbeddingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Embed': grpc.unary_unary_rpc_method_handler(
                    servicer.Embed,
                    request_deserializer=embedding__pb2.EmbedRequest.FromString,
                    response_serializer=embedding__pb2.EmbedResponse.SerializeToString,
            ),
            'BatchEmbed': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchEmbed,
                    request_deserializer=embedding__pb2.BatchEmbedRequest.FromString,
                    response_serializer=embedding__pb2.EmbedResponse.SerializeToString,
            ),
            'GetModelInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelInfo,
                    request_deserializer=embedding__pb2.ModelInfoRequest.FromString,
                    response_serializer=embedding__pb2.ModelInfoResponse.SerializeToString,
            ),
            'ClearCache': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearCache,
                    request_deserializer=embedding__pb2.ClearCacheRequest.FromString,
                    response_serializer=embedding__pb2.ClearCacheResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=embedding__pb2.HealthCheckRequest.FromString,
                    response_serializer=embedding__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent.embedding.EmbeddingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agent.embedding.EmbeddingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EmbeddingService(object):
    """EmbeddingService provides embedding operations
    """

    @staticmethod
    def Embed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.embedding.EmbeddingService/Embed',
            embedding__pb2.EmbedRequest.SerializeToString,
            embedding__pb2.EmbedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchEmbed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.embedding.EmbeddingService/BatchEmbed',
            embedding__pb2.BatchEmbedRequest.SerializeToString,
            embedding__pb2.EmbedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.embedding.EmbeddingService/GetModelInfo',
            embedding__pb2.ModelInfoRequest.SerializeToString,
            embedding__pb2.ModelInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.embedding.EmbeddingService/ClearCache',
            embedding__pb2.ClearCacheRequest.SerializeToString,
            embedding__pb2.ClearCacheResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.embedding.EmbeddingService/HealthCheck',
            embedding__pb2.HealthCheckRequest.SerializeToString,
            embedding__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
