# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embedding.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'embedding.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65mbedding.proto\x12\x0f\x61gent.embedding\"\\\n\x0c\x45mbedRequest\x12\r\n\x05texts\x18\x01 \x03(\t\x12\x11\n\tuse_cache\x18\x02 \x01(\x08\x12\x19\n\x0cmodel_preset\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x0f\n\r_model_preset\"w\n\rEmbedResponse\x12.\n\nembeddings\x18\x01 \x03(\x0b\x32\x1a.agent.embedding.Embedding\x12\r\n\x05model\x18\x02 \x01(\t\x12\x11\n\tdimension\x18\x03 \x01(\x05\x12\x14\n\x0c\x63\x61\x63hed_count\x18\x04 \x01(\x05\"\x1b\n\tEmbedding\x12\x0e\n\x06values\x18\x01 \x03(\x02\"N\n\x11\x42\x61tchEmbedRequest\x12\r\n\x05texts\x18\x01 \x03(\t\x12\x19\n\x0cmodel_preset\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x0f\n\r_model_preset\"\x12\n\x10ModelInfoRequest\"\xa7\x01\n\x11ModelInfoResponse\x12\r\n\x05model\x18\x01 \x01(\t\x12\x11\n\tdimension\x18\x02 \x01(\x05\x12@\n\x07presets\x18\x03 \x03(\x0b\x32/.agent.embedding.ModelInfoResponse.PresetsEntry\x1a.\n\x0cPresetsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x13\n\x11\x43learCacheRequest\"%\n\x12\x43learCacheResponse\x12\x0f\n\x07\x63leared\x18\x01 \x01(\x05\"\x14\n\x12HealthCheckRequest\"[\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\x11\n\tdimension\x18\x03 \x01(\x05\x12\x12\n\ncache_size\x18\x04 \x01(\x05\x32\xb4\x03\n\x10\x45mbeddingService\x12\x46\n\x05\x45mbed\x12\x1d.agent.embedding.EmbedRequest\x1a\x1e.agent.embedding.EmbedResponse\x12P\n\nBatchEmbed\x12\".agent.embedding.BatchEmbedRequest\x1a\x1e.agent.embedding.EmbedResponse\x12U\n\x0cGetModelInfo\x12!.agent.embedding.ModelInfoRequest\x1a\".agent.embedding.ModelInfoResponse\x12U\n\nClearCache\x12\".agent.embedding.ClearCacheRequest\x1a#.agent.embedding.ClearCacheResponse\x12X\n\x0bHealthCheck\x12#.agent.embedding.HealthCheckRequest\x1a$.agent.embedding.HealthCheckResponseBCZAgithub.com/utaaa/uta-travel-agent/internal/gen/go/agent/embeddingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedding_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZAgithub.com/utaaa/uta-travel-agent/internal/gen/go/agent/embedding'
  _globals['_MODELINFORESPONSE_PRESETSENTRY']._loaded_options = None
  _globals['_MODELINFORESPONSE_PRESETSENTRY']._serialized_options = b'8\001'
  _globals['_EMBEDREQUEST']._serialized_start=36
  _globals['_EMBEDREQUEST']._serialized_end=128
  _globals['_EMBEDRESPONSE']._serialized_start=130
  _globals['_EMBEDRESPONSE']._serialized_end=249
  _globals['_EMBEDDING']._serialized_start=251
  _globals['_EMBEDDING']._serialized_end=278
  _globals['_BATCHEMBEDREQUEST']._serialized_start=280
  _globals['_BATCHEMBEDREQUEST']._serialized_end=358
  _globals['_MODELINFOREQUEST']._serialized_start=360
  _globals['_MODELINFOREQUEST']._serialized_end=378
  _globals['_MODELINFORESPONSE']._serialized_start=381
  _globals['_MODELINFORESPONSE']._serialized_end=548
  _globals['_MODELINFORESPONSE_PRESETSENTRY']._serialized_start=502
  _globals['_MODELINFORESPONSE_PRESETSENTRY']._serialized_end=548
  _globals['_CLEARCACHEREQUEST']._serialized_start=550
  _globals['_CLEARCACHEREQUEST']._serialized_end=569
  _globals['_CLEARCACHERESPONSE']._serialized_start=571
  _globals['_CLEARCACHERESPONSE']._serialized_end=608
  _globals['_HEALTHCHECKREQUEST']._serialized_start=610
  _globals['_HEALTHCHECKREQUEST']._serialized_end=630
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=632
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=723
  _globals['_EMBEDDINGSERVICE']._serialized_start=726
  _globals['_EMBEDDINGSERVICE']._serialized_end=1162
# @@protoc_insertion_point(module_scope)
